# Generated by Django 3.0.2 on 2020-02-11 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('drivers_count', models.SmallIntegerField(default=0)),
                ('logo', models.FileField(default='', upload_to='logos/')),
                ('distance', models.PositiveIntegerField(default=0)),
                ('average_fuel', models.FloatField(default=0.0)),
                ('income', models.PositiveIntegerField(default=0)),
                ('waybill_count', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Disposition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('loading_city', models.CharField(max_length=64)),
                ('unloading_city', models.CharField(max_length=64)),
                ('loading_spedition', models.CharField(max_length=100)),
                ('unloading_spedition', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=64)),
                ('tonnage', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disposition_type', models.CharField(choices=[('roz', 'rozpiska'), ('dys', 'dyspozycja')], default='dys', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nick', models.CharField(max_length=64)),
                ('avatar', models.FileField(upload_to='avatars/')),
                ('last_delivery', models.DateTimeField(auto_now_add=True)),
                ('length_of_service', models.DateTimeField(auto_now_add=True)),
                ('position', models.CharField(max_length=20)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hercules_app.Company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gielda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('loading_city', models.CharField(max_length=64)),
                ('unloading_city', models.CharField(max_length=64)),
                ('loading_spedition', models.CharField(max_length=100)),
                ('unloading_spedition', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=64)),
                ('tonnage', models.IntegerField(default=0)),
                ('trailer', models.CharField(choices=[('curt', 'curtain'), ('reef', 'reefer'), ('ldc', 'low_deck'), ('cis', 'cistern'), ('trp', 'tarp')], max_length=8)),
                ('price', models.PositiveIntegerField(default=0)),
                ('creator', models.CharField(default='SYSTEM', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adr', models.BooleanField(default=False)),
                ('oversized', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Waybills',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('loading_city', models.CharField(max_length=64)),
                ('unloading_city', models.CharField(max_length=64)),
                ('loading_spedition', models.CharField(max_length=100)),
                ('unloading_spedition', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=64)),
                ('tonnage', models.IntegerField(default=0)),
                ('fuel', models.IntegerField(default=0)),
                ('damage', models.SmallIntegerField(default=0)),
                ('note', models.TextField(default='')),
                ('status', models.CharField(choices=[('acc', 'accepted'), ('dec', 'declined'), ('edt', 'to_edit'), ('ntc', 'not_checked')], default='ntc', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='WorkApplications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(default='')),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hercules_app.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=80)),
                ('cabin', models.CharField(max_length=64)),
                ('registration_number', models.CharField(max_length=8)),
                ('engine', models.CharField(max_length=100)),
                ('gearbox', models.CharField(max_length=100)),
                ('wheelbase', models.CharField(max_length=4)),
                ('wheels', models.CharField(max_length=75)),
                ('odometer', models.PositiveIntegerField(default=0)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hercules_app.Company')),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hercules_app.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='DriverStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.PositiveIntegerField(default=0)),
                ('tonnage', models.PositiveIntegerField(default=0)),
                ('income', models.PositiveIntegerField(default=0)),
                ('average_fuel', models.FloatField(default=0.0)),
                ('deliveries_count', models.PositiveIntegerField(default=0)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hercules_app.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodic_norm_type', models.CharField(choices=[('wk', 'week'), ('mth', 'month')], default='wk', max_length=5)),
                ('periodic_norm_distance', models.PositiveIntegerField(default=0)),
                ('disposition_norm', models.IntegerField(default=0)),
                ('disposition_norm_type', models.CharField(choices=[('wk', 'week'), ('mth', 'month')], default='wk', max_length=5)),
                ('random_vehicle', models.BooleanField(default=False)),
                ('random_vehicle_timestamp', models.DateTimeField(auto_now_add=True)),
                ('only_assistant', models.BooleanField(default=False)),
                ('auto_synchronization', models.BooleanField(default=False)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hercules_app.Company')),
            ],
        ),
    ]
