# Generated by Django 3.0.2 on 2020-01-31 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Disposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loading_city', models.CharField(max_length=64)),
                ('unloading_city', models.CharField(max_length=64)),
                ('loading_spedition', models.CharField(max_length=100)),
                ('unloading_spedition', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disposition_type', models.CharField(choices=[('roz', 'rozpiska'), ('dys', 'dyspozycja')], default='dys', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=64)),
                ('nick', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=64)),
                ('avatar', models.URLField(max_length=128)),
                ('last_delivery', models.DateTimeField(auto_now_add=True)),
                ('length_of_service', models.DateTimeField(auto_now_add=True)),
                ('position', models.CharField(max_length=20)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hercules_app.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Waybills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loading_city', models.CharField(max_length=64)),
                ('unloading_city', models.CharField(max_length=64)),
                ('loading_spedition', models.CharField(max_length=100)),
                ('unloading_spedition', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('acc', 'accepted'), ('dec', 'declined'), ('edt', 'to_edit'), ('ntc', 'not_checked')], default='ntc', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='WorkApplications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hercules_app.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=80)),
                ('cabin', models.CharField(max_length=64)),
                ('registration_number', models.CharField(max_length=8)),
                ('engine', models.CharField(max_length=100)),
                ('gearbox', models.CharField(max_length=100)),
                ('wheelbase', models.CharField(max_length=4)),
                ('wheels', models.CharField(max_length=75)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hercules_app.Company')),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hercules_app.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='DriverStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hercules_app.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodic_norm_type', models.CharField(choices=[('wk', 'week'), ('mth', 'month')], default='wk', max_length=5)),
                ('disposition_norm_type', models.CharField(choices=[('wk', 'week'), ('mth', 'month')], default='wk', max_length=5)),
                ('random_vehicle_timestamp', models.DateTimeField(auto_now_add=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hercules_app.Company')),
            ],
        ),
    ]
