# Generated by Django 3.0.2 on 2020-05-06 14:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='periodic_norm_end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 6, 14, 37, 41, 182924)),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='periodic_norm_start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 6, 14, 37, 41, 182924)),
        ),
        migrations.AlterField(
            model_name='rozpiska',
            name='fifth_disposition',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fifth_disposition', to='hercules_app.Disposition'),
        ),
        migrations.AlterField(
            model_name='rozpiska',
            name='first_disposition',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_disposition', to='hercules_app.Disposition'),
        ),
        migrations.AlterField(
            model_name='rozpiska',
            name='fourth_disposition',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fourth_disposition', to='hercules_app.Disposition'),
        ),
        migrations.AlterField(
            model_name='rozpiska',
            name='second_disposition',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_disposition', to='hercules_app.Disposition'),
        ),
        migrations.AlterField(
            model_name='rozpiska',
            name='third_disposition',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_disposition', to='hercules_app.Disposition'),
        ),
    ]
