# Generated by Django 3.0.2 on 2020-01-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gielda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loading_city', models.CharField(max_length=64)),
                ('unloading_city', models.CharField(max_length=64)),
                ('loading_spedition', models.CharField(max_length=100)),
                ('unloading_spedition', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=64)),
                ('trailer', models.CharField(choices=[('curt', 'curtain'), ('reef', 'reefer'), ('ldc', 'low_deck'), ('cis', 'cistern'), ('trp', 'tarp')], max_length=8)),
                ('creator', models.CharField(default='SYSTEM', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adr', models.BooleanField(default=False)),
                ('oversized', models.BooleanField(default=False)),
            ],
        ),
    ]
