# Generated by Django 3.0.2 on 2020-04-19 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='periodic_norm_end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 16, 46, 44, 898146)),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='periodic_norm_start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 16, 46, 44, 898146)),
        ),
    ]
