# Generated by Django 3.0.2 on 2020-05-09 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0002_auto_20200506_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='engine_power',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='periodic_norm_end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 18, 56, 0, 453613)),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='periodic_norm_start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 18, 56, 0, 453613)),
        ),
    ]
