# Generated by Django 3.0.2 on 2020-05-09 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0003_auto_20200509_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='periodic_norm_end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 18, 58, 46, 195737)),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='periodic_norm_start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 18, 58, 46, 195737)),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_power',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
