# Generated by Django 3.0.2 on 2020-04-23 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0003_auto_20200423_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='waybill',
            name='reject_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='waybill',
            name='to_edit_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='periodic_norm_end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 23, 16, 50, 3, 998981)),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='periodic_norm_start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 23, 16, 50, 3, 998981)),
        ),
    ]
