# Generated by Django 3.0.2 on 2020-04-24 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0004_auto_20200423_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='max_90',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='periodic_norm_end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 24, 13, 49, 17, 415571)),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='periodic_norm_start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 24, 13, 49, 17, 415571)),
        ),
    ]
