# Generated by Django 3.0.2 on 2020-02-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0004_auto_20200211_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='avatar',
            field=models.FileField(null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='nick',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='position',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
