# Generated by Django 3.0.2 on 2020-03-04 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0005_auto_20200213_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='company_id',
            new_name='company',
        ),
    ]
