# Generated by Django 3.0.2 on 2020-04-24 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0005_auto_20200424_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='url',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='periodic_norm_end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 24, 14, 30, 57, 776847)),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='periodic_norm_start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 24, 14, 30, 57, 776847)),
        ),
    ]
