# Generated by Django 3.0.2 on 2020-05-18 12:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0005_auto_20200511_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='workapplications',
            name='about_me',
            field=models.TextField(default='', max_length=2500),
        ),
        migrations.AddField(
            model_name='workapplications',
            name='age',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workapplications',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hercules_app.Company'),
        ),
        migrations.AddField(
            model_name='workapplications',
            name='controller',
            field=models.CharField(blank=True, default='', max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='workapplications',
            name='dlc',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='workapplications',
            name='steam_profile',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='workapplications',
            name='town',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='workapplications',
            name='truckers_mp_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='periodic_norm_end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 18, 12, 23, 44, 136067)),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='periodic_norm_start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 18, 12, 23, 44, 136067)),
        ),
    ]
