# Generated by Django 3.0.2 on 2020-04-24 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0006_auto_20200424_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='url',
            new_name='communicator_url',
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='periodic_norm_end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 24, 14, 56, 1, 919129)),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='periodic_norm_start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 24, 14, 56, 1, 919129)),
        ),
    ]
