# Generated by Django 3.0.2 on 2020-03-04 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0006_auto_20200304_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companysettings',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='driverstatistics',
            old_name='driver_id',
            new_name='driver',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='driver_id',
            new_name='driver',
        ),
        migrations.RenameField(
            model_name='workapplications',
            old_name='driver_id',
            new_name='driver',
        ),
    ]
