# Generated by Django 3.0.2 on 2020-05-18 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0006_auto_20200518_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workapplications',
            name='description',
        ),
        migrations.AddField(
            model_name='workapplications',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('declined', 'declined'), ('not-checked', 'not_checked')], default='not-checked', max_length=12),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='periodic_norm_end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 18, 16, 52, 38, 203224)),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='periodic_norm_start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 18, 16, 52, 38, 203224)),
        ),
    ]
