# Generated by Django 3.0.2 on 2020-04-24 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0007_auto_20200424_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='is_recruiting',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='periodic_norm_end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 24, 16, 36, 38, 356125)),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='periodic_norm_start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 24, 16, 36, 38, 356125)),
        ),
    ]
