# Generated by Django 3.0.2 on 2020-03-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0007_auto_20200304_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(choices=[('man', 'MAN'), ('merc', 'Mercedes-Benz'), ('daf', 'DAF'), ('ren', 'Renault'), ('sca', 'Scania'), ('ive', 'Iveco')], default='man', max_length=20),
        ),
    ]
