# Generated by Django 3.0.2 on 2020-05-20 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0008_auto_20200518_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workapplications',
            name='controller',
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='periodic_norm_end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 12, 11, 6, 75582)),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='periodic_norm_start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 12, 11, 6, 75582)),
        ),
    ]
