# Generated by Django 3.0.2 on 2020-03-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0008_auto_20200304_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(choices=[('MAN', 'MAN'), ('Mercedes-Benz', 'Mercedes-Benz'), ('DAF', 'DAF'), ('Renault', 'Renault'), ('Scania', 'Scania'), ('Iveco', 'Iveco')], default='MAN', max_length=20),
        ),
    ]
