# Generated by Django 3.0.2 on 2020-04-24 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0008_auto_20200424_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='dlc',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='periodic_norm_end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 24, 17, 32, 0, 10611)),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='periodic_norm_start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 24, 17, 32, 0, 10611)),
        ),
    ]
