# Generated by Django 3.0.2 on 2020-05-21 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0009_auto_20200520_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckersMPStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulation_1_players', models.PositiveIntegerField(default=0)),
                ('simulation_2_players', models.PositiveIntegerField(default=0)),
                ('promods_players', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='fuel',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='periodic_norm_end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 21, 12, 33, 45, 28370)),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='periodic_norm_start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 21, 12, 33, 45, 28370)),
        ),
    ]
