# Generated by Django 3.0.2 on 2020-03-04 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0009_auto_20200304_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposition',
            name='driver',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hercules_app.Driver'),
        ),
    ]
