# Generated by Django 3.0.2 on 2020-04-25 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0009_auto_20200424_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='random_vehicle_type',
            field=models.CharField(choices=[('wk', 'week'), ('mth', 'month')], default='wk', max_length=5),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='periodic_norm_end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 25, 12, 53, 2, 22871)),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='periodic_norm_start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 25, 12, 53, 2, 22871)),
        ),
    ]
