# Generated by Django 3.0.6 on 2020-05-21 17:21

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0011_auto_20200521_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckersmpstatus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='periodic_norm_end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 21, 17, 21, 26, 773013)),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='periodic_norm_start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 21, 17, 21, 26, 773013)),
        ),
    ]
