# Generated by Django 3.0.2 on 2020-03-13 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0011_remove_disposition_disposition_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Waybills',
            new_name='Waybill',
        ),
        migrations.CreateModel(
            name='Screenshots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f6_screen', models.FileField(upload_to='media/')),
                ('end_screen', models.FileField(upload_to='media/')),
                ('waybill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hercules_app.Waybill')),
            ],
        ),
    ]
