# Generated by Django 3.0.2 on 2020-03-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0012_auto_20200313_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='waybill',
            name='end_screen',
            field=models.FileField(default='', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='waybill',
            name='f6_screen',
            field=models.FileField(default='', upload_to='media/'),
        ),
        migrations.DeleteModel(
            name='Screenshots',
        ),
    ]
