# Generated by Django 3.0.6 on 2020-05-23 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0012_auto_20200521_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='periodic_norm_end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 23, 17, 2, 50, 818931)),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='periodic_norm_start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 23, 17, 2, 50, 818931)),
        ),
        migrations.AlterField(
            model_name='workapplications',
            name='driver',
            field=models.CharField(default='', max_length=128),
        ),
    ]
