# Generated by Django 3.0.6 on 2020-05-25 15:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0013_auto_20200523_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='periodic_norm_end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 25, 15, 25, 48, 241297)),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='periodic_norm_start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 25, 15, 25, 48, 241297)),
        ),
        migrations.AlterField(
            model_name='driver',
            name='avatar',
            field=models.ImageField(default='avatars/avatar-placeholder.png', null=True, upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hercules_app.Company'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='position',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='photo',
            field=models.ImageField(blank=True, default='vehicles/truck-placeholder.jpg', null=True, upload_to='vehicles'),
        ),
    ]
