# Generated by Django 3.0.2 on 2020-03-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0013_auto_20200313_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
