# Generated by Django 3.0.2 on 2020-03-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0014_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AlterField(
            model_name='waybill',
            name='end_screen',
            field=models.ImageField(default='', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='f6_screen',
            field=models.ImageField(default='', upload_to='media/', verbose_name='f6_screen'),
        ),
    ]
