# Generated by Django 3.0.6 on 2020-05-26 13:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0014_auto_20200525_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='last_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_name', to='hercules_app.Driver'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='periodic_norm_end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 13, 47, 55, 780017)),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='periodic_norm_start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 13, 47, 55, 780017)),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='random_vehicle_type',
            field=models.CharField(blank=True, choices=[('wk', 'Tydzień'), ('mth', 'Miesiąc')], default='wk', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='avatar',
            field=models.ImageField(default='avatars/avatar-placeholder.jpg', null=True, upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='hercules_app.Driver'),
        ),
    ]
