# Generated by Django 3.0.6 on 2020-06-05 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0015_auto_20200526_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='periodic_norm_end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 5, 12, 15, 6, 154286)),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='periodic_norm_start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 5, 12, 15, 6, 154286)),
        ),
        migrations.AlterField(
            model_name='disposition',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
