# Generated by Django 3.0.2 on 2020-03-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0015_auto_20200314_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waybill',
            name='f6_screen',
        ),
        migrations.AddField(
            model_name='waybill',
            name='first_screen',
            field=models.ImageField(default='', upload_to='media/', verbose_name='first_screen'),
        ),
    ]
