# Generated by Django 3.0.2 on 2020-03-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0016_auto_20200318_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybill',
            name='first_screen',
            field=models.ImageField(default='', upload_to='media/'),
        ),
    ]
