# Generated by Django 3.0.3 on 2020-03-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0017_auto_20200318_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='waybill',
            name='distance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='waybill',
            name='income',
            field=models.IntegerField(default=0),
        ),
    ]
