# Generated by Django 3.0.6 on 2020-06-10 16:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0017_auto_20200606_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='periodic_norm_end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 10, 16, 3, 1, 337384)),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='periodic_norm_start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 10, 16, 3, 1, 337384)),
        ),
        migrations.CreateModel(
            name='WaybillImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loading_info', models.ImageField(default='', upload_to='waybills')),
                ('unloading_info', models.ImageField(default='', upload_to='waybills')),
                ('cargo_image', models.ImageField(default='', upload_to='waybills')),
                ('tonnage_image', models.ImageField(default='', upload_to='waybills')),
                ('distance_image', models.ImageField(default='', upload_to='waybills')),
                ('fuel_image', models.ImageField(default='', upload_to='waybills')),
                ('income_image', models.ImageField(default='', upload_to='waybills')),
                ('waybill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hercules_app.Waybill')),
            ],
        ),
    ]
