# Generated by Django 3.0.6 on 2020-06-14 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0018_auto_20200610_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waybill',
            name='screens_id',
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='periodic_norm_end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 14, 14, 32, 22, 536203)),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='periodic_norm_start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 14, 14, 32, 22, 536203)),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='loading_country',
            field=models.CharField(default='no_country', max_length=100),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='loading_spedition',
            field=models.CharField(default='no_company', max_length=100),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='unloading_country',
            field=models.CharField(default='no_country', max_length=100),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='unloading_spedition',
            field=models.CharField(default='no_company', max_length=100),
        ),
    ]
