# Generated by Django 3.0.2 on 2020-04-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0018_auto_20200326_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_employeed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driverstatistics',
            name='fuel',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
