# Generated by Django 3.0.2 on 2020-04-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0019_auto_20200404_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gielda',
            name='trailer',
            field=models.CharField(choices=[('Firanka', 'curtain'), ('Chłodnia', 'reefer'), ('Niskopodłgowa', 'low_deck'), ('Cysterna', 'cistern'), ('Plandeka', 'tarp')], max_length=13),
        ),
    ]
