# Generated by Django 3.0.2 on 2020-04-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0020_auto_20200406_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='gielda',
            name='loading_country',
            field=models.CharField(default='none', max_length=64),
        ),
        migrations.AddField(
            model_name='gielda',
            name='unloading_country',
            field=models.CharField(default='none', max_length=64),
        ),
    ]
