# Generated by Django 3.0.2 on 2020-04-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0021_auto_20200406_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gielda',
            name='adr',
            field=models.CharField(choices=[('ADR-1: materiały wybuchowe', 'explosives'), ('ADR-2: gazy', 'gases'), ('ADR-3: płyny łatwopalne', 'liquids'), ('ADR-4: materiały stałe zapalne', 'solids'), ('ADR-6: toksyczne i zakaźne substancje', 'toxic'), ('ADR-8: toksyczne substancje', 'corrosive')], max_length=64),
        ),
        migrations.AlterField(
            model_name='gielda',
            name='loading_country',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='gielda',
            name='trailer',
            field=models.CharField(choices=[('Firanka', 'curtain'), ('Chłodnia', 'reefer'), ('Niskopodłogowa', 'low_deck'), ('Cysterna', 'cistern'), ('Plandeka', 'tarp')], max_length=14),
        ),
        migrations.AlterField(
            model_name='gielda',
            name='unloading_country',
            field=models.CharField(max_length=64),
        ),
    ]
