# Generated by Django 3.0.2 on 2020-04-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0022_auto_20200409_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gielda',
            name='adr',
            field=models.CharField(choices=[('Nie dotyczy', 'none'), ('ADR-1: materiały wybuchowe', 'explosives'), ('ADR-2: gazy', 'gases'), ('ADR-3: płyny łatwopalne', 'liquids'), ('ADR-4: materiały stałe zapalne', 'solids'), ('ADR-6: toksyczne i zakaźne substancje', 'toxic'), ('ADR-8: toksyczne substancje', 'corrosive')], max_length=64),
        ),
    ]
