# Generated by Django 3.0.3 on 2020-04-10 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0023_auto_20200409_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposition',
            name='is_rozpiska',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Rozpiska',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rozpiska_id', models.IntegerField(default=0)),
                ('first_disposition_id', models.IntegerField(default=0)),
                ('second_disposition_id', models.IntegerField(default=0)),
                ('third_disposition_id', models.IntegerField(default=0)),
                ('fourth_disposition_id', models.IntegerField(default=0)),
                ('fifth_disposition_id', models.IntegerField(default=0)),
                ('driver', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hercules_app.Driver')),
            ],
        ),
        migrations.AddField(
            model_name='disposition',
            name='rozpiska',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hercules_app.Rozpiska'),
        ),
    ]
