# Generated by Django 3.0.3 on 2020-04-10 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0024_auto_20200410_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposition',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
