# Generated by Django 3.0.6 on 2020-06-14 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0024_auto_20200614_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='periodic_norm_end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 14, 16, 15, 46, 684950)),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='periodic_norm_start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 14, 16, 15, 46, 684950)),
        ),
        migrations.AlterField(
            model_name='gielda',
            name='adr',
            field=models.CharField(choices=[('Nie dotyczy', 'none'), ('ADR-1: materiały wybuchowe', 'explosives'), ('ADR-2: gazy', 'gases'), ('ADR-3: płyny łatwopalne', 'liquids'), ('ADR-4: materiały stałe zapalne', 'solids'), ('ADR-6: toksyczne i zakaźne substancje', 'toxic'), ('ADR-8: toksyczne substancje', 'corrosive')], default='none', max_length=64, null=True),
        ),
    ]
