# Generated by Django 3.0.3 on 2020-04-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0025_disposition_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposition',
            name='loading_country',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='disposition',
            name='unloading_country',
            field=models.CharField(default='', max_length=64),
        ),
    ]
