# Generated by Django 3.0.3 on 2020-04-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0026_auto_20200410_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposition',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
