# Generated by Django 3.0.3 on 2020-04-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0027_disposition_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_recruiting',
            field=models.BooleanField(default=True),
        ),
    ]
