# Generated by Django 3.0.2 on 2020-04-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0028_company_is_recruiting'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_ats',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_ets2',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_multiplayer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_promods',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_singleplayer',
            field=models.BooleanField(default=True),
        ),
    ]
