# Generated by Django 3.0.2 on 2020-04-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0029_auto_20200411_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='is_ats',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='is_ets2',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='is_multiplayer',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='is_promods',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='is_singleplayer',
        ),
        migrations.AddField(
            model_name='company',
            name='is_ats',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='is_ets2',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='is_multiplayer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='is_promods',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='is_singleplayer',
            field=models.BooleanField(default=True),
        ),
    ]
