# Generated by Django 3.0.2 on 2020-04-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0033_auto_20200411_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(default='', upload_to='static/logos'),
        ),
    ]
