# Generated by Django 3.0.2 on 2020-04-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0034_auto_20200411_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(default='', upload_to='logos'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='end_screen',
            field=models.ImageField(default='', upload_to='waybills'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='first_screen',
            field=models.ImageField(default='', upload_to='waybills'),
        ),
    ]
