# Generated by Django 3.0.2 on 2020-04-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0035_auto_20200413_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='photo',
            field=models.ImageField(null=True, upload_to='vehicles'),
        ),
    ]
