# Generated by Django 3.0.2 on 2020-04-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0036_vehicle_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tonnage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
