# Generated by Django 3.0.2 on 2020-04-15 10:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0037_company_tonnage'),
    ]

    operations = [
        migrations.AddField(
            model_name='waybill',
            name='driver',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hercules_app.Driver'),
        ),
        migrations.AddField(
            model_name='waybill',
            name='finish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='waybill',
            name='loading_country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='waybill',
            name='unloading_country',
            field=models.CharField(default='', max_length=100),
        ),
    ]
