# Generated by Django 3.0.2 on 2020-04-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0038_auto_20200415_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybill',
            name='finish_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
