# Generated by Django 3.0.2 on 2020-04-15 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0039_auto_20200415_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybill',
            name='driver',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hercules_app.Driver'),
        ),
    ]
