# Generated by Django 3.0.2 on 2020-04-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0041_auto_20200415_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybill',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('declined', 'declined'), ('to-edit', 'to_edit'), ('not-checked', 'not_checked')], default='not-checked', max_length=12),
        ),
    ]
