# Generated by Django 3.0.2 on 2020-04-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0042_auto_20200415_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='waybill',
            name='screens_id',
            field=models.CharField(default='', max_length=72),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
