# Generated by Django 3.0.2 on 2020-04-17 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0043_auto_20200415_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hercules_app.Company'),
        ),
    ]
