# Generated by Django 3.0.2 on 2020-04-17 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0044_auto_20200417_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hercules_app.Driver'),
        ),
    ]
