# Generated by Django 3.0.2 on 2020-04-18 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0046_auto_20200418_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_timer', models.BooleanField(default=True)),
                ('eco_driver', models.BooleanField(default=False)),
                ('long_distance_driver', models.BooleanField(default=False)),
                ('heavy_driver', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hercules_app.Driver')),
            ],
        ),
    ]
