# Generated by Django 3.0.2 on 2020-04-18 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0047_achievement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rozpiska',
            name='fifth_disposition_id',
        ),
        migrations.RemoveField(
            model_name='rozpiska',
            name='first_disposition_id',
        ),
        migrations.RemoveField(
            model_name='rozpiska',
            name='fourth_disposition_id',
        ),
        migrations.RemoveField(
            model_name='rozpiska',
            name='second_disposition_id',
        ),
        migrations.RemoveField(
            model_name='rozpiska',
            name='third_disposition_id',
        ),
        migrations.AddField(
            model_name='rozpiska',
            name='fifth_disposition',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='fifth_disposition', to='hercules_app.Disposition'),
        ),
        migrations.AddField(
            model_name='rozpiska',
            name='first_disposition',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='first_disposition', to='hercules_app.Disposition'),
        ),
        migrations.AddField(
            model_name='rozpiska',
            name='fourth_disposition',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='fourth_disposition', to='hercules_app.Disposition'),
        ),
        migrations.AddField(
            model_name='rozpiska',
            name='second_disposition',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='second_disposition', to='hercules_app.Disposition'),
        ),
        migrations.AddField(
            model_name='rozpiska',
            name='third_disposition',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='third_disposition', to='hercules_app.Disposition'),
        ),
    ]
