# Generated by Django 3.0.2 on 2020-04-18 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hercules_app', '0048_auto_20200418_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposition',
            name='rozpiska',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='hercules_app.Rozpiska'),
        ),
    ]
